/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    BaseLayout: typeof import('./components/BaseLayout.vue')['default']
    copy: typeof import('./components/ToDoList copy.vue')['default']
    FanyList: typeof import('./components/FanyList.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    NDateInput: typeof import('./components/NDateInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlotContent: typeof import('./components/SlotContent.vue')['default']
    SubmitButton: typeof import('./components/SubmitButton.vue')['default']
    ToDoCard: typeof import('./components/ToDoCard.vue')['default']
    'ToDoCard copy': typeof import('./components/ToDoCard copy.vue')['default']
    ToDoList: typeof import('./components/ToDoList.vue')['default']
    'ToDoList copy': typeof import('./components/ToDoList copy.vue')['default']
  }
}
