/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ArrayClassBind': RouteRecordInfo<
      '/ArrayClassBind',
      '/ArrayClassBind',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/CachedPropFunc': RouteRecordInfo<
      '/CachedPropFunc',
      '/CachedPropFunc',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/CheckboxFormBind': RouteRecordInfo<
      '/CheckboxFormBind',
      '/CheckboxFormBind',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ClassBind': RouteRecordInfo<
      '/ClassBind',
      '/ClassBind',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ClassBindComponent': RouteRecordInfo<
      '/ClassBindComponent',
      '/ClassBindComponent',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ComputedProp': RouteRecordInfo<
      '/ComputedProp',
      '/ComputedProp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/RadioSelectFormBind_2': RouteRecordInfo<
      '/RadioSelectFormBind_2',
      '/RadioSelectFormBind_2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/RadioSelectFormBind copy': RouteRecordInfo<
      '/RadioSelectFormBind copy',
      '/RadioSelectFormBind%20copy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/StyleBind': RouteRecordInfo<
      '/StyleBind',
      '/StyleBind',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/TextFormBind': RouteRecordInfo<
      '/TextFormBind',
      '/TextFormBind',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/TodoList': RouteRecordInfo<
      '/TodoList',
      '/TodoList',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/VTextFields': RouteRecordInfo<
      '/VTextFields',
      '/VTextFields',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/VTextFields_2': RouteRecordInfo<
      '/VTextFields_2',
      '/VTextFields_2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/VueList': RouteRecordInfo<
      '/VueList',
      '/VueList',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/WritableComputed': RouteRecordInfo<
      '/WritableComputed',
      '/WritableComputed',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ArrayClassBind.vue': {
      routes:
        | '/ArrayClassBind'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/CachedPropFunc.vue': {
      routes:
        | '/CachedPropFunc'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/CheckboxFormBind.vue': {
      routes:
        | '/CheckboxFormBind'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ClassBind.vue': {
      routes:
        | '/ClassBind'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ClassBindComponent.vue': {
      routes:
        | '/ClassBindComponent'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ComputedProp.vue': {
      routes:
        | '/ComputedProp'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/RadioSelectFormBind_2.vue': {
      routes:
        | '/RadioSelectFormBind_2'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/RadioSelectFormBind copy.vue': {
      routes:
        | '/RadioSelectFormBind copy'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/StyleBind.vue': {
      routes:
        | '/StyleBind'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/TextFormBind.vue': {
      routes:
        | '/TextFormBind'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/TodoList.vue': {
      routes:
        | '/TodoList'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/VTextFields.vue': {
      routes:
        | '/VTextFields'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/VTextFields_2.vue': {
      routes:
        | '/VTextFields_2'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/VueList.vue': {
      routes:
        | '/VueList'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/WritableComputed.vue': {
      routes:
        | '/WritableComputed'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
