/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/AxiosGet': RouteRecordInfo<
      '/AxiosGet',
      '/AxiosGet',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/CreateToDo': RouteRecordInfo<
      '/CreateToDo',
      '/CreateToDo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/DynamicSlotName': RouteRecordInfo<
      '/DynamicSlotName',
      '/DynamicSlotName',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/item.[itemid]': RouteRecordInfo<
      '/item.[itemid]',
      '/item/:itemid',
      { itemid: ParamValue<true> },
      { itemid: ParamValue<false> },
      | never
    >,
    '/LoginAccount': RouteRecordInfo<
      '/LoginAccount',
      '/LoginAccount',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/MyComponent': RouteRecordInfo<
      '/MyComponent',
      '/MyComponent',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/NamedScopedSlot': RouteRecordInfo<
      '/NamedScopedSlot',
      '/NamedScopedSlot',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/NamedSlot': RouteRecordInfo<
      '/NamedSlot',
      '/NamedSlot',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ParentComponent': RouteRecordInfo<
      '/ParentComponent',
      '/ParentComponent',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ProfileAccount': RouteRecordInfo<
      '/ProfileAccount',
      '/ProfileAccount',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/RegisterAccount': RouteRecordInfo<
      '/RegisterAccount',
      '/RegisterAccount',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ScopedSlot': RouteRecordInfo<
      '/ScopedSlot',
      '/ScopedSlot',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ScopedSlotComponent': RouteRecordInfo<
      '/ScopedSlotComponent',
      '/ScopedSlotComponent',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/SlotContent': RouteRecordInfo<
      '/SlotContent',
      '/SlotContent',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/AxiosGet.vue': {
      routes:
        | '/AxiosGet'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/CreateToDo.vue': {
      routes:
        | '/CreateToDo'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/DynamicSlotName.vue': {
      routes:
        | '/DynamicSlotName'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/item.[itemid].vue': {
      routes:
        | '/item.[itemid]'
      views:
        | never
      pathParamNames:
        | 'itemid'
    }
    'src/pages/LoginAccount.vue': {
      routes:
        | '/LoginAccount'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/MyComponent.vue': {
      routes:
        | '/MyComponent'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/NamedScopedSlot.vue': {
      routes:
        | '/NamedScopedSlot'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/NamedSlot.vue': {
      routes:
        | '/NamedSlot'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ParentComponent.vue': {
      routes:
        | '/ParentComponent'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ProfileAccount.vue': {
      routes:
        | '/ProfileAccount'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/RegisterAccount.vue': {
      routes:
        | '/RegisterAccount'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ScopedSlot.vue': {
      routes:
        | '/ScopedSlot'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ScopedSlotComponent.vue': {
      routes:
        | '/ScopedSlotComponent'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/SlotContent.vue': {
      routes:
        | '/SlotContent'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
