/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/BlogPage': RouteRecordInfo<
      '/BlogPage',
      '/BlogPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/BlogPageEmitStandalone': RouteRecordInfo<
      '/BlogPageEmitStandalone',
      '/BlogPageEmitStandalone',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/BlogPageVFor': RouteRecordInfo<
      '/BlogPageVFor',
      '/BlogPageVFor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/BlohPageEmit': RouteRecordInfo<
      '/BlohPageEmit',
      '/BlohPageEmit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ComponentRef': RouteRecordInfo<
      '/ComponentRef',
      '/ComponentRef',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ComponentSlot': RouteRecordInfo<
      '/ComponentSlot',
      '/ComponentSlot',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/LifeCycleHookPage': RouteRecordInfo<
      '/LifeCycleHookPage',
      '/LifeCycleHookPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ParentComp': RouteRecordInfo<
      '/ParentComp',
      '/ParentComp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ParentCompIn': RouteRecordInfo<
      '/ParentCompIn',
      '/ParentCompIn',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ParentCompIn2': RouteRecordInfo<
      '/ParentCompIn2',
      '/ParentCompIn2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ParentCompParam': RouteRecordInfo<
      '/ParentCompParam',
      '/ParentCompParam',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/ParentCompParam2': RouteRecordInfo<
      '/ParentCompParam2',
      '/ParentCompParam2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/TemplateRef': RouteRecordInfo<
      '/TemplateRef',
      '/TemplateRef',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/YesNoQuestion': RouteRecordInfo<
      '/YesNoQuestion',
      '/YesNoQuestion',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/BlogPage.vue': {
      routes:
        | '/BlogPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/BlogPageEmitStandalone.vue': {
      routes:
        | '/BlogPageEmitStandalone'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/BlogPageVFor.vue': {
      routes:
        | '/BlogPageVFor'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/BlohPageEmit.vue': {
      routes:
        | '/BlohPageEmit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ComponentRef.vue': {
      routes:
        | '/ComponentRef'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ComponentSlot.vue': {
      routes:
        | '/ComponentSlot'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/LifeCycleHookPage.vue': {
      routes:
        | '/LifeCycleHookPage'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ParentComp.vue': {
      routes:
        | '/ParentComp'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ParentCompIn.vue': {
      routes:
        | '/ParentCompIn'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ParentCompIn2.vue': {
      routes:
        | '/ParentCompIn2'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ParentCompParam.vue': {
      routes:
        | '/ParentCompParam'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ParentCompParam2.vue': {
      routes:
        | '/ParentCompParam2'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/TemplateRef.vue': {
      routes:
        | '/TemplateRef'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/YesNoQuestion.vue': {
      routes:
        | '/YesNoQuestion'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
